-- Create stories table
create table if not exists stories (
  id bigint generated by default as identity primary key,
  title text,
  story text not null,
  analysis text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create characters table
create table if not exists characters (
  id bigint generated by default as identity primary key,
  story_id bigint not null references stories(id) on delete cascade,
  name text not null,
  mentions integer not null,
  description text,
  attributes text,
  relationships text,
  image_url text
);

-- Create scenes table
create table if not exists scenes (
  id bigint generated by default as identity primary key,
  story_id bigint not null references stories(id) on delete cascade,
  scene_id integer not null,
  title text not null,
  description text,
  setting text,
  time_of_day text,
  mood text,
  key_actions text,
  characters text,
  objects text,
  emotions text,
  image_url text
);

-- Create models table for storing model names and links
create table if not exists models (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null, -- 'character' or 'scene'
  link text not null,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create users table for authentication
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  role text not null default 'unpaid', -- 'root', 'admin', 'paid', 'unpaid'
  verified boolean not null default false, -- Whether the user's account is verified
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add verified column to existing users table if it doesn't exist
ALTER TABLE users ADD COLUMN IF NOT EXISTS verified boolean NOT NULL DEFAULT false;

-- Insert default models
insert into models (name, type, link, is_default) values 
  ('nano-banana', 'character', 'https://fal.run/fal-ai/nano-banana/', true),
  ('flux-dev', 'scene', 'https://fal.run/fal-ai/flux/dev', true)
on conflict (name) do nothing;

-- Create indexes for better performance
create index if not exists idx_characters_story_id on characters(story_id);
create index if not exists idx_scenes_story_id on scenes(story_id);
create index if not exists idx_scenes_scene_id on scenes(scene_id);
create index if not exists idx_models_type on models(type);
create index if not exists idx_users_username on users(username);
create index if not exists idx_users_role on users(role);
create index if not exists idx_users_verified on users(verified);