-- Create stories table
create table if not exists stories (
  id bigint generated by default as identity primary key,
  title text,
  story text not null,
  analysis text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create characters table
create table if not exists characters (
  id bigint generated by default as identity primary key,
  story_id bigint not null references stories(id) on delete cascade,
  name text not null,
  mentions integer not null,
  description text,
  attributes text,
  relationships text,
  image_url text
);

-- Create scenes table
create table if not exists scenes (
  id bigint generated by default as identity primary key,
  story_id bigint not null references stories(id) on delete cascade,
  scene_id integer not null,
  title text not null,
  description text,
  setting text,
  time_of_day text,
  mood text,
  key_actions text,
  characters text,
  objects text,
  emotions text,
  image_url text
);

-- Create indexes for better performance
create index if not exists idx_characters_story_id on characters(story_id);
create index if not exists idx_scenes_story_id on scenes(story_id);
create index if not exists idx_scenes_scene_id on scenes(scene_id);